### PR TITLE
fix exception No such type, issue 154

### PR DESCRIPTION
**Pull request by Lana243**

### CODE REVIEW

**Comment by operasfantom** [comment]
@Lana243 Can you add the simple test suite of 2 files that reflects the changes, please?

**Comment by Lana243** [comment]
> @Lana243 Can you add the simple test suite of 2 files that reflects the changes, please?

@operasfantom, should it be integration or unit test?

**Comment by operasfantom** [comment]
> > @Lana243 Can you add the simple test suite of 2 files that reflects the changes, please?
> 
> @operasfantom, should it be integration or unit test?

Unit test is enough, look at regression suite as an example

**Review by operasfantom — APPROVED** [review]
LGTM

**Pull request merged**
