### PR TITLE
Add shared matrix.json for actions

### PR DESCRIPTION
**Pull request by ladisgin**

### CODE REVIEW

**Comment by korifey** [comment]
@akuleshov7 could you please tell is "matrix" the only way to parametrize the build?

**Comment by petertrr** [comment]
> @akuleshov7 @petertrr could you please tell is "matrix" the only way to parametrize the build?

There is also an option with triggering a workflow manually and providing parameters as inputs: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_dispatch. I haven't tried this approach myself, though.

In our projects the only parameter we use is a git tag, and we deduce current version from it. We use matrix only when it's required to execute CI in different environments, like different OS, different JDK version and so on.

**Comment by akuleshov7** [comment]
@korifey also there is no mechanism for sharing the os matrix between actions, and I suppose it is done intentionally. In this case you will always understand what you are doing and in which OS. 

Are you sure that you really need that?

**Comment by korifey** [comment]
@akuleshov7 in our build, we have to make **same** dependency in several places of yml. 
Also because of [this issue](https://github.com/actions/runner/issues/480) it can't be parametrized normally.

**Comment by korifey** [comment]
> > @akuleshov7 @petertrr could you please tell is "matrix" the only way to parametrize the build?
> 
> There is also an option with triggering a workflow manually and providing parameters as inputs: https://docs.github.com/en/actions/learn-github-actions/events-that-trigger-workflows#workflow_dispatch. I haven't tried this approach myself, though.
> 
> In our projects the only parameter we use is a git tag, and we deduce current version from it. We use matrix only when it's required to execute CI in different environments, like different OS, different JDK version and so on.

@petertrr here I misused word "parameter". I mean that we need some constants storage, like .properties in Java for deduplication.

**Comment by korifey** [comment]
@ladisgin LGTM!

**Pull request merged**
